--CAU 1
CREATE TABLE VATTU (
	MAVT CHAR(4) PRIMARY KEY,
	TENVT NVARCHAR(20),
	DVTINH NVARCHAR(10) ,
	SLCON INT
)
GO

CREATE TABLE HDBAN (
	MAHD VARCHAR(10) PRIMARY KEY,
	NGAYXUAT SMALLDATETIME,
	HOTENKHACH NVARCHAR(20)
)
GO

CREATE TABLE HANGXUAT(
	MAHD VARCHAR(10),
	MAVT CHAR(4),
	DONGIA MONEY,
	SLBAN INT,
	CONSTRAINT pk_hx PRIMARY KEY(MAHD, MAVT)
)
GO

INSERT INTO VATTU(MAVT,TENVT,DVTINH,SLCON) VALUES (N'VT01', N'XI MANG', 'VND', 100)
INSERT INTO VATTU(MAVT,TENVT,DVTINH,SLCON) VALUES(N'VT02', N'CAT', 'VND', 200)
INSERT INTO HDBAN(MAHD,NGAYXUAT,HOTENKHACH) VALUES(N'HD0058',CAST(N'2022-10-3'AS DATE),N'TRAN QUOC THANG  ')
INSERT INTO HDBAN(MAHD,NGAYXUAT,HOTENKHACH) VALUES(N'HD0064',CAST(N'2022-9-5'AS DATE),N'CAO THI TUYET TRINH ')
INSERT INTO HANGXUAT(MAHD,MAVT,DONGIA,SLBAN) VALUES(N'HD0058',N'VT01',100000, 200)
INSERT INTO HANGXUAT(MAHD,MAVT,DONGIA,SLBAN) VALUES(N'HD0059',N'VT01',200000, 400)
INSERT INTO HANGXUAT(MAHD,MAVT,DONGIA,SLBAN) VALUES(N'HD0061',N'VT02',100000, 300)
INSERT INTO HANGXUAT(MAHD,MAVT,DONGIA,SLBAN) VALUES(N'HD0062',N'VT02',100000, 100)


--CAU 2
select top 1 MAHD, sum(DONGIA) as TongTien from HANGXUAT group by MAHD,
DONGIA order by DONGIA desc
--CAU 3
GO
CREATE FUNCTION C3 (
    @MAHD varchar(10)
)
RETURNS TABLE
AS
RETURN
    SELECT 
        HX.MAHD,
        HD.NGAYXUAT,
        HX.MAVT,
        HX.DONGIA,
        HX.SLBAN,  
        CASE
            WHEN DATENAME(dw,HD.NGAYXUAT) = 'Monday' THEN N'Thứ hai'            
            WHEN DATENAME(dw,HD.NGAYXUAT) = 'Tuesday' THEN N'Thứ ba'
            WHEN DATENAME(dw,HD.NGAYXUAT) = 'Wednesday' THEN N'Thứ tư'
            WHEN DATENAME(dw,HD.NGAYXUAT) = 'Thursday' THEN N'Thứ năm'
            WHEN DATENAME(dw,HD.NGAYXUAT) = 'Friday' THEN N'Thứ sáu'
            WHEN DATENAME(dw,HD.NGAYXUAT) = 'Saturday' THEN N'Thứ bảy'
            ELSE N'Chủ nhật'
        END AS NGAYTHU

    FROM HANGXUAT HX
    INNER JOIN HDBAN HD ON HX.MAHD = HD.MAHD
    WHERE HX.MAHD = @MAHD;
GO


--CAU 4
CREATE PROCEDURE C4 
@thang int, @nam int 
AS
SELECT 
SUM(SLBAN * DONGIA)
FROM HANGXUAT HX
INNER JOIN HDBAN HD ON HX.MAHD = HD.MAHD
where MONTH(HD.NGAYXUAT) = @THANG AND YEAR(HD.NGAYXUAT) = @NAM;
select top 1 MAHD, sum(DONGIA) as TongTien from HANGXUAT group by MAHD,
DONGIA order by DONGIA desc
